/* WADRA Bay v11 — Départ 3 : 3-TD-LT1 */
BASE.zones.push({
  "id": 3, "tab": "3-TD-LT1", "title": "DÉPART 3/10 : TD-LT1 — Local Technique 1", "ref": "TD-LT1 — Local Technique 1 | 130 kVA | 187,6 A | 42C45",
  "equipments": [
    {"n": "1", "aRelever": "NON", "equipement": "Climatiseur (split réversible)", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'C1'", "notice": "✓", "marque": "GREE", "aVerifier": "Relever plaque — RELEVER 1 BUNGALOW TYPE"},
    {"n": "2", "aRelever": "OUI", "equipement": "PAC ECS bungalow Lagune", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Sous-bassement bungalow", "ref": "Schéma 42C53", "notice": "✗", "aVerifier": "Relever 1 type"},
    {"n": "3", "aRelever": "NON", "equipement": "VMC / extraction", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'VMC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "4", "aRelever": "OUI", "equipement": "Mini-bar / réfrigérateur", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Mini-bar'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "5", "aRelever": "OUI", "equipement": "Téléviseur", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "6", "aRelever": "OUI", "equipement": "Pompe (booster ECS)", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Pompe'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "7", "aRelever": "OUI", "equipement": "Borne / prise extérieure", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Terrasse", "ref": "Schéma 42C53 'Bornes'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "8", "aRelever": "OUI", "equipement": "Coffre-fort + sèche-cheveux", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "9", "aRelever": "NON", "equipement": "Module domotique KNX", "qte": "1", "local": "TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'GTC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "10", "aRelever": "NON", "equipement": "Éclairage intérieur + terrasse", "local": "TT-LAG — Bungalows Lagune · Bungalow + terrasse", "ref": "Plan lustrerie EL06", "notice": "✓", "aVerifier": "Relever 1 bungalow type"},
    {"n": "11", "aRelever": "OUI", "equipement": "Lave-linge lingerie", "qte": "1", "local": "TT-Lingerie — Lingerie LT1 · Lingerie LT1", "notice": "✗", "aVerifier": "Relever"},
    {"n": "12", "aRelever": "OUI", "equipement": "Sèche-linge lingerie", "qte": "1", "local": "TT-Lingerie — Lingerie LT1 · Lingerie LT1", "notice": "✗", "aVerifier": "Relever"},
    {"n": "13", "aRelever": "OUI", "equipement": "Éclairage + prises lingerie", "qte": "1", "local": "TT-Lingerie — Lingerie LT1 · Lingerie LT1", "notice": "✗", "aVerifier": "Relever"},
    {"n": "14", "aRelever": "OUI", "equipement": "Éclairage & prises communs (THQ-LT1)", "qte": "1", "local": "THQ-LT1 — Tableau éclairage / prises communs LT1 · Local technique 1", "notice": "✗", "aVerifier": "Relever"},
    {"n": "15", "aRelever": "NON", "equipement": "Climatiseur (split réversible)", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'C1'", "notice": "✓", "marque": "GREE", "aVerifier": "Relever plaque — RELEVER 1 BUNGALOW TYPE"},
    {"n": "16", "aRelever": "OUI", "equipement": "PAC ECS bungalow Lagune", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Sous-bassement bungalow", "ref": "Schéma 42C53", "notice": "✗", "aVerifier": "Relever 1 type"},
    {"n": "17", "aRelever": "NON", "equipement": "VMC / extraction", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'VMC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "18", "aRelever": "OUI", "equipement": "Mini-bar / réfrigérateur", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Mini-bar'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "19", "aRelever": "OUI", "equipement": "Téléviseur", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "20", "aRelever": "OUI", "equipement": "Pompe (booster ECS)", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Pompe'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "21", "aRelever": "OUI", "equipement": "Borne / prise extérieure", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Terrasse", "ref": "Schéma 42C53 'Bornes'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "22", "aRelever": "OUI", "equipement": "Coffre-fort + sèche-cheveux", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "23", "aRelever": "NON", "equipement": "Module domotique KNX", "qte": "1", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'GTC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "24", "aRelever": "NON", "equipement": "Éclairage intérieur + terrasse", "local": "TD-LT2 · TT-LAG — Bungalows Lagune · Bungalow + terrasse", "ref": "Plan lustrerie EL06", "notice": "✓", "aVerifier": "Relever 1 bungalow type"},
    {"n": "25", "aRelever": "OUI", "equipement": "Éclairage & prises communs (THQ-LT2)", "qte": "1", "local": "TD-LT2 · THQ-LT2 · Local technique 2", "notice": "✗", "aVerifier": "Relever"},
    {"n": "26", "aRelever": "OUI", "equipement": "Éclairage & prises communs (THQ-LT3)", "qte": "1", "local": "TD-LT3 · THQ-LT3 · Local technique 3", "notice": "✗", "aVerifier": "Relever"},
    {"n": "27", "aRelever": "NON", "equipement": "Climatiseur (split réversible)", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'C1'", "notice": "✓", "marque": "GREE", "aVerifier": "Relever plaque — RELEVER 1 BUNGALOW TYPE"},
    {"n": "28", "aRelever": "OUI", "equipement": "PAC ECS bungalow Lagune", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Sous-bassement bungalow", "ref": "Schéma 42C53", "notice": "✗", "aVerifier": "Relever 1 type"},
    {"n": "29", "aRelever": "NON", "equipement": "VMC / extraction", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'VMC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "30", "aRelever": "OUI", "equipement": "Mini-bar / réfrigérateur", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Mini-bar'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "31", "aRelever": "OUI", "equipement": "Téléviseur", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "32", "aRelever": "OUI", "equipement": "Pompe (booster ECS)", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'Pompe'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "33", "aRelever": "OUI", "equipement": "Borne / prise extérieure", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Terrasse", "ref": "Schéma 42C53 'Bornes'", "notice": "✗", "aVerifier": "Relever"},
    {"n": "34", "aRelever": "OUI", "equipement": "Coffre-fort + sèche-cheveux", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Présomption", "notice": "✗", "aVerifier": "Relever"},
    {"n": "35", "aRelever": "NON", "equipement": "Module domotique KNX", "qte": "1", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow", "ref": "Schéma 42C53 'GTC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "36", "aRelever": "NON", "equipement": "Éclairage intérieur + terrasse", "local": "TD-LT3 · TT-LAG — Bungalows Lagune · Bungalow + terrasse", "ref": "Plan lustrerie EL06", "notice": "✓", "aVerifier": "Relever 1 bungalow type"},
    {"n": "37", "aRelever": "OUI", "equipement": "Réfrigérateur fitness", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · Salle fitness", "ref": "Schéma 42C55", "notice": "✗", "aVerifier": "Relever"},
    {"n": "38", "aRelever": "OUI", "equipement": "Pompe SPA", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · Local technique SPA", "ref": "Schéma 42C55", "notice": "✗", "aVerifier": "Relever plaque"},
    {"n": "39", "aRelever": "OUI", "equipement": "Sonorisation SPA / Fitness", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA", "ref": "Schéma 42C55", "notice": "✗", "aVerifier": "Relever"},
    {"n": "40", "aRelever": "NON", "equipement": "Équipements fitness (tapis, vélos)", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · Salle fitness", "ref": "Devis Techno Gym", "notice": "✓", "marque": "Techno Gym", "modele": "voir devis", "aVerifier": "Confirmer la liste"},
    {"n": "41", "aRelever": "OUI", "equipement": "Jacuzzi", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA", "ref": "—", "notice": "✗", "aVerifier": "Confirmer présence"},
    {"n": "42", "aRelever": "OUI", "equipement": "Sauna", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA", "ref": "—", "notice": "✗", "aVerifier": "Confirmer présence + puissance résistances"},
    {"n": "43", "aRelever": "OUI", "equipement": "Hammam (générateur de vapeur)", "qte": "1", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA", "ref": "—", "notice": "✗", "aVerifier": "Confirmer présence"},
    {"n": "44", "aRelever": "NON", "equipement": "Climatisation SPA / Fitness", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA / salle fitness", "ref": "Schéma 42C55 'CLIM'", "notice": "✓", "marque": "GREE", "aVerifier": "Relever groupe(s) + unités"},
    {"n": "45", "aRelever": "NON", "equipement": "Extraction SPA", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA", "ref": "Schéma 42C55 'Extr'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "46", "aRelever": "NON", "equipement": "Éclairage SPA / Fitness", "local": "TD-LT3 · TT-SPA — SPA / Fitness · SPA / fitness", "ref": "Plans EL11 / CL11", "notice": "✓", "aVerifier": "Relever"},
    {"n": "47", "aRelever": "NON", "equipement": "Machine à glaçons — Office", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Office", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "48", "aRelever": "OUI", "equipement": "Plancha Sea Food", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Cuisine Sea Food", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Plaque — PRIORITÉ mesure"},
    {"n": "49", "aRelever": "OUI", "equipement": "Barbecue Sea Food", "qte": "3", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Cuisine Sea Food", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Relever (3 unités)"},
    {"n": "50", "aRelever": "OUI", "equipement": "Hotte Sea Food + caisson", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Cuisine Sea Food", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Débit + moteur"},
    {"n": "51", "aRelever": "OUI", "equipement": "Lave-vaisselle / plonge Sea Food", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Office SF", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Relever"},
    {"n": "52", "aRelever": "OUI", "equipement": "Meubles réfrigérés Sea Food", "qte": "2", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Sea Food", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Relever"},
    {"n": "53", "aRelever": "NON", "equipement": "Perco", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Sea Food", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "54", "aRelever": "OUI", "equipement": "PAC ECS Sea Food", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Sea Food", "ref": "Schéma 42C60", "notice": "✗", "aVerifier": "Relever"},
    {"n": "55", "aRelever": "NON", "equipement": "Climatisation Sea Food", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Sea Food", "ref": "Schéma 42C61 TC Sea Food", "notice": "✓", "marque": "GREE", "aVerifier": "Relever"},
    {"n": "56", "aRelever": "OUI", "equipement": "Éclairage Sea Food", "qte": "1", "local": "TD-LT3 · TT-SEAFOOD — Restaurant Sea Food · Sea Food", "notice": "✗", "aVerifier": "Relever"},
    {"n": "57", "aRelever": "OUI", "equipement": "Lave-linge lingerie", "qte": "1", "local": "TD-LT3 · TT-Lingerie3 — Lingerie LT3 · Lingerie LT3", "notice": "✗", "aVerifier": "Relever"},
    {"n": "58", "aRelever": "OUI", "equipement": "Sèche-linge lingerie", "qte": "1", "local": "TD-LT3 · TT-Lingerie3 — Lingerie LT3 · Lingerie LT3", "notice": "✗", "aVerifier": "Relever"},
    {"n": "59", "aRelever": "OUI", "equipement": "Éclairage + prises lingerie", "qte": "1", "local": "TD-LT3 · TT-Lingerie3 — Lingerie LT3 · Lingerie LT3", "notice": "✗", "aVerifier": "Relever"}
  ]
});
