/* WADRA Bay v11 — Départ 2 : 2-TG-C */
BASE.zones.push({
  "id": 2, "tab": "2-TG-C", "title": "DÉPART 2/10 : TG-C — Cœur du site", "ref": "TG-C — Cœur du site | 110,9 kVA | 160 A",
  "equipments": [
    {"n": "1", "aRelever": "NON", "equipement": "Four mixte électrique", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Plaque kW — PRIORITÉ mesure"},
    {"n": "2", "aRelever": "NON", "equipement": "Plaque à induction", "qte": "2", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Puissance de plaque"},
    {"n": "3", "aRelever": "NON", "equipement": "Salamandre suspendue", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "4", "aRelever": "NON", "equipement": "Bain-marie électrique", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "5", "aRelever": "NON", "equipement": "Passe chauffe-plat", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "6", "aRelever": "NON", "equipement": "Thermoplongeur 1200 W", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Confirmer (1,2 kW)"},
    {"n": "7", "aRelever": "NON", "equipement": "Cuiseur de riz 10 L", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "8", "aRelever": "NON", "equipement": "Fumoir électrique", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "9", "aRelever": "NON", "equipement": "Toasteur convoyeur", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "10", "aRelever": "NON", "equipement": "Élément self distributeur chaud 3 bacs", "qte": "1", "local": "TD-Cuisine · Cafétéria", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "11", "aRelever": "NON", "equipement": "Four micro-ondes", "qte": "2", "local": "TD-Cuisine · Cuisine / Cafétéria", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "12", "aRelever": "NON", "equipement": "Cellule de refroidissement", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Compresseur — PRIORITÉ mesure"},
    {"n": "13", "aRelever": "NON", "equipement": "Congélateur coffre 200 L", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "14", "aRelever": "NON", "equipement": "Meuble adossé réfrigéré 2 portes", "qte": "3", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever (3 unités)"},
    {"n": "15", "aRelever": "NON", "equipement": "Saladette 3 portes", "qte": "1", "local": "TD-Cuisine · Cuisine principale", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "16", "aRelever": "NON", "equipement": "Meuble bas réfrigéré 3 portes", "qte": "1", "local": "TD-Cuisine · Garde manger", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "17", "aRelever": "NON", "equipement": "Meuble réfrigéré saladette 2 portes", "qte": "1", "local": "TD-Cuisine · Garde manger", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "18", "aRelever": "NON", "equipement": "Armoire réfrigérée 1 porte", "qte": "4", "local": "TD-Cuisine · Cuisine / Garde manger / Cafét.", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever (4 unités)"},
    {"n": "19", "aRelever": "NON", "equipement": "Armoire réfrigérée 2 portes", "qte": "1", "local": "TD-Cuisine · Zone déboitage", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "20", "aRelever": "NON", "equipement": "Meuble adossé réfrigéré 3 portes (pâtisserie)", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "21", "aRelever": "NON", "equipement": "Armoire négative 1 porte", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "22", "aRelever": "NON", "equipement": "Armoire positive 1 porte", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "23", "aRelever": "NON", "equipement": "Chambre de pousse", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "24", "aRelever": "NON", "equipement": "Élément self distributeur froid 3 bacs", "qte": "1", "local": "TD-Cuisine · Cafétéria", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "25", "aRelever": "NON", "equipement": "Fontaine réfrigérée", "qte": "1", "local": "TD-Cuisine · Cafétéria", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "26", "aRelever": "NON", "equipement": "Machine à glaçons (déboitage)", "qte": "1", "local": "TD-Cuisine · Zone déboitage", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "27", "aRelever": "OUI", "equipement": "Chambre froide positive", "qte": "1", "local": "TD-Cuisine · Local CF", "ref": "Schéma 42C - FROID", "notice": "✗", "aVerifier": "Compresseur — PRIORITÉ mesure"},
    {"n": "28", "aRelever": "OUI", "equipement": "Chambre froide négative", "qte": "1", "local": "TD-Cuisine · Local CF", "ref": "Schéma 42C - FROID", "notice": "✗", "aVerifier": "Compresseur — PRIORITÉ mesure"},
    {"n": "29", "aRelever": "NON", "equipement": "Éplucheuse à légumes", "qte": "1", "local": "TD-Cuisine · Légumerie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "30", "aRelever": "NON", "equipement": "Râpe à coco électrique", "qte": "1", "local": "TD-Cuisine · Légumerie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "31", "aRelever": "NON", "equipement": "Lave-vaisselle à capot", "qte": "1", "local": "TD-Cuisine · Plonge", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Plaque — PRIORITÉ mesure"},
    {"n": "32", "aRelever": "NON", "equipement": "Machine sous vide", "qte": "1", "local": "TD-Cuisine · Garde manger", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "33", "aRelever": "NON", "equipement": "Hachoir", "qte": "1", "local": "TD-Cuisine · Garde manger", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "34", "aRelever": "NON", "equipement": "Trancheuse électrique", "qte": "1", "local": "TD-Cuisine · Garde manger", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "35", "aRelever": "NON", "equipement": "Laminoir Dito Sama", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "36", "aRelever": "NON", "equipement": "Pétrin mélangeur", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "37", "aRelever": "NON", "equipement": "Batteur mélangeur", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "38", "aRelever": "NON", "equipement": "Sorbetière 5 L", "qte": "1", "local": "TD-Cuisine · Pâtisserie", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "39", "aRelever": "NON", "equipement": "Machine à café", "qte": "1", "local": "TD-Cuisine · Cafétéria", "ref": "Inventaire MAINTENANCE", "notice": "✓", "aVerifier": "Relever"},
    {"n": "40", "aRelever": "NON", "equipement": "Petit matériel divers (blenders, mixeurs...)", "qte": "~15", "local": "TD-Cuisine · Cuisine (toutes zones)", "ref": "Inventaire MAINTENANCE", "notice": "✓", "modele": "divers", "aVerifier": "Comptage global"},
    {"n": "41", "aRelever": "OUI", "equipement": "Hotte d'extraction cuisson", "qte": "1", "local": "TD-Cuisine · Zone cuisson", "ref": "Présomption", "notice": "✗", "aVerifier": "Débit + puissance moteur"},
    {"n": "42", "aRelever": "NON", "equipement": "Éclairage cuisine et annexes", "local": "TD-Cuisine · Cuisine", "ref": "Plan EL02 CUIS-ADMIN", "notice": "✓", "aVerifier": "Relever"},
    {"n": "43", "aRelever": "OUI", "equipement": "Imprimantes, photocopieurs", "local": "TD-ACCUEIL · Accueil", "ref": "Présomption", "notice": "✗", "aVerifier": "Comptage global"},
    {"n": "44", "aRelever": "NON", "equipement": "Climatisation Accueil / réception", "local": "TD-ACCUEIL · Accueil", "ref": "Schéma 42C34b TC-Accueil", "notice": "✓", "marque": "GREE", "aVerifier": "Relever groupes + unités"},
    {"n": "45", "aRelever": "NON", "equipement": "Éclairage Accueil / réception", "local": "TD-ACCUEIL · Accueil", "ref": "Plan EL02 + LUST01", "notice": "✓", "aVerifier": "Relever"},
    {"n": "46", "aRelever": "OUI", "equipement": "Prises & matériel comptoir réception", "qte": "1", "local": "TD-ACCUEIL · Accueil", "notice": "✗", "aVerifier": "Relever"},
    {"n": "47", "aRelever": "OUI", "equipement": "Serveur informatique central", "qte": "1", "local": "TD-ADMIN · Local serveur", "ref": "Présomption", "notice": "✗", "aVerifier": "Poste continu 24/24"},
    {"n": "48", "aRelever": "OUI", "equipement": "Postes informatiques / bureautique", "qte": "~10", "local": "TD-ADMIN · Bureaux admin", "ref": "Présomption", "notice": "✗", "aVerifier": "Comptage global"},
    {"n": "49", "aRelever": "OUI", "equipement": "Système GTB / GTC / supervision", "qte": "1", "local": "TD-ADMIN · Local technique", "ref": "Repère 'GTB'", "notice": "✗", "aVerifier": "Recenser — pilotage du site"},
    {"n": "50", "aRelever": "NON", "equipement": "Climatisation bureaux administration", "qte": "4", "local": "TD-ADMIN · Bureaux admin", "ref": "Schéma 42C44a 'C1'", "notice": "✓", "marque": "GREE", "aVerifier": "4 climatiseurs — relever plaques"},
    {"n": "51", "aRelever": "NON", "equipement": "Climatisation dédiée local serveur", "qte": "1", "local": "TD-ADMIN · Local serveur", "ref": "Présomption", "notice": "✓", "marque": "GREE", "aVerifier": "Confirmer — fonctionne 24/24"},
    {"n": "52", "aRelever": "NON", "equipement": "VMC + ventilateur d'extraction", "local": "TD-ADMIN · Bureaux admin", "ref": "Schéma 42C44a 'VMC'", "notice": "✓", "aVerifier": "Relever"},
    {"n": "53", "aRelever": "OUI", "equipement": "Éclairage bureaux administration", "qte": "1", "local": "TD-ADMIN · Bureaux admin", "notice": "✗", "aVerifier": "Relever"},
    {"n": "54", "aRelever": "NON", "equipement": "Tireuse à bière + refroidisseur de fût", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "marque": "Gamko", "aVerifier": "Plaque du groupe froid"},
    {"n": "55", "aRelever": "NON", "equipement": "Machine à glaçons — Bar", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "56", "aRelever": "NON", "equipement": "Machine à paillette 85 kg/j", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "57", "aRelever": "NON", "equipement": "Machine à glaçons — Sea Food", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "58", "aRelever": "NON", "equipement": "Lave-verres", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Schéma 42C35a", "notice": "✓", "aVerifier": "Relever"},
    {"n": "59", "aRelever": "NON", "equipement": "Meuble bas réfrigéré 2 portes vitrées", "qte": "3", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever (3 unités)"},
    {"n": "60", "aRelever": "NON", "equipement": "Meuble réfrigéré 2 portes pleines", "qte": "2", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "61", "aRelever": "NON", "equipement": "Tiroir à bouteilles réfrigéré", "qte": "3", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "62", "aRelever": "NON", "equipement": "Cave à vin 110 bouteilles", "qte": "3", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "aVerifier": "Relever"},
    {"n": "63", "aRelever": "NON", "equipement": "Refroidisseur de fût Gamko 3/4", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "marque": "Gamko", "aVerifier": "Relever"},
    {"n": "64", "aRelever": "NON", "equipement": "Machine à café Nespresso Gemini", "qte": "2", "local": "TD-FARE-BAR · Bar", "ref": "Inventaire RESTO BAR", "notice": "✓", "marque": "Nespresso", "modele": "Gemini", "aVerifier": "Relever"},
    {"n": "65", "aRelever": "OUI", "equipement": "Ballon ECS Bar", "qte": "1", "local": "TD-FARE-BAR · Bar", "ref": "Schéma 42C35a", "notice": "✗", "aVerifier": "Relever capacité + puissance"},
    {"n": "66", "aRelever": "NON", "equipement": "Climatisation Bar", "local": "TD-FARE-BAR · Bar", "ref": "Schéma 42C35b TC-Bar", "notice": "✓", "marque": "GREE", "aVerifier": "Relever"},
    {"n": "67", "aRelever": "OUI", "equipement": "Éclairage Bar", "qte": "1", "local": "TD-FARE-BAR · Bar", "notice": "✗", "aVerifier": "Relever"},
    {"n": "68", "aRelever": "OUI", "equipement": "Ballon ECS Restaurant", "qte": "1", "local": "TD-RESTAURANT · Restaurant", "ref": "Schéma 42C36a", "notice": "✗", "aVerifier": "Relever"},
    {"n": "69", "aRelever": "NON", "equipement": "Climatisation Restaurant", "local": "TD-RESTAURANT · Restaurant", "ref": "Schéma 42C36b TC-Resto", "notice": "✓", "marque": "GREE", "aVerifier": "Poste important — relever groupes"},
    {"n": "70", "aRelever": "OUI", "equipement": "Éclairage Restaurant", "qte": "1", "local": "TD-RESTAURANT · Restaurant", "notice": "✗", "aVerifier": "Relever"},
    {"n": "71", "aRelever": "NON", "equipement": "Pompe de filtration piscine principale", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "42C37 + notice", "notice": "✓", "marque": "Waterco", "modele": "Hydrostar MK4/Plus", "aVerifier": "3 à 11 kW — modèle exact sur plaque"},
    {"n": "72", "aRelever": "NON", "equipement": "Pompe de filtration piscine secours", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Schéma 42C37", "notice": "✓", "marque": "Waterco", "modele": "Hydrostar", "aVerifier": "Confirmer la présence"},
    {"n": "73", "aRelever": "NON", "equipement": "Filtre à sable piscine", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Notice Waterco", "notice": "✓", "marque": "Waterco", "modele": "série S", "aVerifier": "Ø cuve + modèle"},
    {"n": "74", "aRelever": "NON", "equipement": "Pompe doseuse chlore", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Notice Concept-Plus", "notice": "✓", "marque": "Concept-Plus", "modele": "péristaltique", "aVerifier": "< 0,1 kW"},
    {"n": "75", "aRelever": "NON", "equipement": "Pompe doseuse pH", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Notice Concept-Plus", "notice": "✓", "marque": "Concept-Plus", "modele": "péristaltique", "aVerifier": "Relever"},
    {"n": "76", "aRelever": "NON", "equipement": "Électrolyseur traitement eau", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Notice ROX", "notice": "✓", "marque": "ROX", "modele": "électrolyseur", "aVerifier": "Confirmer présence"},
    {"n": "77", "aRelever": "OUI", "equipement": "Programmateur horaire filtration", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "—", "notice": "✗", "aVerifier": "Modèle + plages horaires"},
    {"n": "78", "aRelever": "OUI", "equipement": "Pompe Faré Piscine", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Schéma 42C39", "notice": "✗", "aVerifier": "Relever plaque"},
    {"n": "79", "aRelever": "OUI", "equipement": "Chauffage piscine (PAC ?)", "qte": "1", "local": "LT-PISCINE · LT-Piscine", "ref": "Présomption", "notice": "✗", "aVerifier": "Confirmer présence + type"},
    {"n": "80", "aRelever": "NON", "equipement": "Éclairage local technique", "local": "LT-PISCINE · LT-Piscine", "ref": "Plans EL03/EL04", "notice": "✓", "aVerifier": "Relever"},
    {"n": "81", "aRelever": "OUI", "equipement": "PAC ECS centrale", "qte": "1", "local": "TD-SANITAIRES · Local sanitaires", "ref": "Schéma 42C38", "notice": "✗", "aVerifier": "Type PAC + COP sur plaque"},
    {"n": "82", "aRelever": "OUI", "equipement": "Ballon ECS centrale", "qte": "1", "local": "TD-SANITAIRES · Local sanitaires", "ref": "Schéma 42C38", "notice": "✗", "aVerifier": "Capacité + puissance appoint"},
    {"n": "83", "aRelever": "OUI", "equipement": "Pompe de bouclage ECS", "qte": "1", "local": "TD-SANITAIRES · Local sanitaires", "ref": "Schémas 42C", "notice": "✗", "aVerifier": "Anti-légionellose"},
    {"n": "84", "aRelever": "OUI", "equipement": "Sèche-mains électriques", "local": "TD-SANITAIRES · Local sanitaires", "ref": "Schéma 42C38", "notice": "✗", "aVerifier": "Compter + relever puissance"},
    {"n": "85", "aRelever": "NON", "equipement": "Éclairage local Production ECS", "local": "TD-SANITAIRES · Local sanitaires", "ref": "Schéma 42C38", "notice": "✓", "aVerifier": "Relever"},
    {"n": "86", "aRelever": "NON", "equipement": "Éclairage extérieur voiries / espaces verts", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Voiries / espaces verts", "ref": "Plans EL00.1/00.2 VRD", "notice": "✓", "aVerifier": "Relever bornes + projecteurs"},
    {"n": "87", "aRelever": "NON", "equipement": "Éclairage de sécurité (BAES)", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Tout le site", "ref": "Dossier partagé 08", "notice": "✓", "aVerifier": "Compter + relever"},
    {"n": "88", "aRelever": "OUI", "equipement": "Surpresseur / pompe d'arrosage", "qte": "1", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Local technique extérieur", "ref": "Présomption", "notice": "✗", "aVerifier": "Confirmer + relever"},
    {"n": "89", "aRelever": "OUI", "equipement": "Portails / barrières motorisés", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Accès site", "ref": "Présomption", "notice": "✗", "aVerifier": "Recenser"},
    {"n": "90", "aRelever": "OUI", "equipement": "Bornes de recharge véhicules (IRVE)", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Parking", "ref": "Présomption", "notice": "✗", "aVerifier": "Confirmer présence"},
    {"n": "91", "aRelever": "NON", "equipement": "Luminaires LED + drivers", "local": "Éclairage extérieur & VRD (départ aval TG-C) · Tout le site", "ref": "Dossier partagé 08", "notice": "✓", "modele": "drivers SNP20-VF", "aVerifier": "Croiser avec l'inventaire 08-Éclairage"}
  ]
});
