/* WADRA Bay — point de départ du module Hébergements :
   « Rapport Bungalows & Chambres » de JC ALIKIE, mercredi 22 mars 2026.
   Chaque clé : items { point: [état, note] } avec état ok / att (à surveiller) / hs,
   et todos (travaux à faire). Les points non cités dans le rapport restent
   « non vérifiés ». Les clés 303, 312, 313, 316, 317 et 415 n'y figurent pas. */
window.WADRA_HEBG_SEED = {
  /* ---------- Villas Plage ---------- */
  "101": { items: { clim_salon: ["ok"], clim_ch: ["ok"], pac: ["ok"], tv_salon: ["ok"], tv_ch: ["ok"], wifi: ["ok"], spa: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "102": { items: { clim_salon: ["hs", "code erreur Pc / PA"], clim_ch: ["hs", "code erreur Pc / PA"], pac: ["ok"], tv_salon: ["hs"], tv_ch: ["hs"], wifi: ["ok"], spa: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "103": { items: { clim_salon: ["hs", "code erreur Pc / L3"], clim_ch: ["hs", "code erreur E6 / Pc"], pac: ["hs", "fuite importante"], tv_salon: ["hs"], tv_ch: ["hs"], wifi: ["ok"], spa: ["hs", "code erreur HL — capteur / sonde de température HS"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Ruban LED sous le deck à l'entrée HS"] },
  "104": { items: { clim_salon: ["ok"], clim_ch: ["ok"], pac: ["ok"], tv_salon: ["ok"], tv_ch: ["ok"], wifi: ["ok"], spa: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "105": { items: { clim_salon: ["hs", "code erreur E6"], clim_ch: ["hs", "code erreur E6"], pac: ["ok"], tv_salon: ["ok"], tv_ch: ["ok"], wifi: ["ok"], spa: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  /* ---------- Bungalows Forêt ---------- */
  "201": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["hs", "sous le deck devant la porte d'entrée"] } },
  "202": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "203": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "204": { items: { clim: ["hs", "code erreur P6"], pac: ["hs"], tv: ["hs", "TV + décodeur Canal sat à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["hs", "marches d'escalier 12, 14, 16 et 18, côté droit"] } },
  /* ---------- Chambres bâtiments N et O ---------- */
  "301": { items: { clim: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Transfo à installer (alimentation LED douche)"] },
  "302": { items: { clim: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], brasseur: ["att", "manque la télécommande"] } },
  "304": { items: { clim: ["att", "condensation de la tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "305": { items: { clim: ["att", "condensation de la tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "306": { items: { clim: ["hs"], tv: ["hs", "TV et CANAL+ à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], brasseur: ["hs"] }, todos: ["Transfo à installer (alimentation LED douche)"] },
  "307": { items: { clim: ["hs"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], plomb: ["att", "lavabo : l'eau ne s'évacue pas rapidement"] } },
  "308": { items: { clim: ["att", "condensation sur tuyauterie"], tv: ["hs", "TV OK, CANAL+ HS : manque le décodeur"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Retouche finition du faux plafond autour du spot à l'entrée de la chambre"] },
  "309": { items: { clim: ["att", "condensation sur tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "310": { items: { clim: ["att", "condensation sur tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "311": { items: { clim: ["ok"], tv: ["hs", "manque le décodeur"], brasseur: ["hs"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Piles HS (télécommande)"] },
  "314": { items: { clim: ["att", "condensation sous le clim et tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "315": { items: { clim: ["att", "condensation sous le clim et de la tuyauterie"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "318": { items: { tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "319": { items: { clim: ["att", "condensation à la sortie de l'air"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "320": { items: { clim: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "321": { items: { clim: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], plomb: ["att", "lavabo : l'eau ne s'évacue pas rapidement"] } },
  "322": { items: { clim: ["att", "condensation sortie air frais"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], plomb: ["att", "chasse d'eau à revoir"] } },
  /* ---------- Bungalows Lagune ---------- */
  "401": { items: { clim: ["hs", "condensation à contrôler"], pac: ["ok"], tv: ["hs", "TV & CANAL+ à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Régler la porte de douche intérieure", "Reprendre la finition du faux plafond du salon et de la salle de bain", "Installer les pommes de douche (extérieure et intérieure)", "Régler le joint d'étanchéité en bas de la porte d'entrée", "Deck d'entrée à nettoyer"] },
  "402": { items: { clim: ["att", "condensation à contrôler"], pac: ["ok"], tv: ["hs", "TV OK, CANAL+ HS : manque le décodeur"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Reprendre la finition du faux plafond du salon et de la salle de bain", "Nettoyer le deck à l'entrée"] },
  "403": { items: { clim: ["att", "condensation à contrôler"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Reprendre la finition du faux plafond du salon", "Installer la pomme de douche extérieure", "Deck d'entrée à nettoyer"] },
  "404": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "405": { items: { clim: ["att", "à contrôler (condensation)"], tv: ["hs", "TV & décodeur CANAL+ à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Reprendre la finition du faux plafond du salon"] },
  "406": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Deck d'entrée à nettoyer"] },
  "407": { items: { clim: ["ok"], pac: ["ok"], tv: ["att", "image trouble (CANAL+ OK)"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Régler la porte de douche intérieure", "Installer la pomme de douche extérieure"] },
  "408": { items: { clim: ["hs", "code erreur PH"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Deck de la douche extérieure à nettoyer"] },
  "409": { items: { clim: ["hs"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], plomb: ["att", "eau chaude / eau froide inversées au lavabo de gauche"] },
           todos: ["Inverser les tuyauteries eau chaude / eau froide du lavabo de gauche", "Decks à l'entrée et vers la douche extérieure à nettoyer"] },
  "410": { items: { clim: ["hs", "code erreur E8"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "411": { items: { clim: ["att", "condensation à contrôler"], pac: ["ok"], tv: ["hs", "TV OK, CANAL+ à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"], plomb: ["hs", "chasse d'eau HS"] },
           todos: ["Chasse d'eau HS à revoir", "Reprendre la finition du faux plafond du salon", "Trappe à réparer (modifier le système de fermeture)"] },
  "412": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "413": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] } },
  "414": { items: { clim: ["att", "condensation à contrôler"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Reprendre la finition du faux plafond du salon"] },
  "416": { items: { clim: ["ok"], pac: ["ok"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] }, todos: ["Régler la porte de douche intérieure (frotte contre le parquet)"] },
  "417": { items: { clim: ["hs", "compresseur à changer"], pac: ["att", "purger le réservoir"], tv: ["hs", "TV HS ; CANAL+ : manque le décodeur"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Régler la porte de douche intérieure"] },
  "418": { items: { clim: ["ok"], pac: ["att", "purger le réservoir"], tv: ["ok"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["att", "disjoncteur E4 éclairage terrasse disjoncte"], brasseur: ["att", "télécommande HS"], plomb: ["att", "eau chaude / eau froide inversées au lavabo de gauche"] },
           todos: ["Inverser eau chaude / eau froide du lavabo de gauche", "Régler la porte de douche intérieure", "Installer les pommes de douche intérieure et extérieure", "Télécommande du brasseur d'air HS à remplacer", "Disjoncteur E4 (éclairage terrasse) disjoncte : à diagnostiquer"] },
  "419": { items: { clim: ["att", "condensation à contrôler"], pac: ["att", "purger le réservoir"], tv: ["hs", "TV & CANAL+ à installer"], wifi: ["ok"], ecl_int: ["ok"], ecl_ext: ["ok"] },
           todos: ["Faux plafond à reprendre (salon et salle de bain)", "Installer les pommes de douche intérieure et extérieure", "Reprendre la fixation du panneau de douche extérieure"] }
};
